server.port=8081
scraper.base-url=${SCRAPER_BASE_URL:http://host.docker.internal:3001}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rootpassword}
spring.jpa.hibernate.ddl-auto=update
jwt.secret=${JWT_SECRET}
gemini.api.key=${GEMINI_API_KEY}
groq.api.key=${GROQ_API_KEY}
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
x.api-key=${X_API_KEY}
x.api-key-secret=${X_API_KEY_SECRET}
x.access-token=${X_ACCESS_TOKEN}
x.access-token-secret=${X_ACCESS_TOKEN_SECRET}
linkedin.client-id=${LINKEDIN_CLIENT_ID}
linkedin.client-secret=${LINKEDIN_CLIENT_SECRET}
linkedin.redirect-uri=${LINKEDIN_REDIRECT_URI}
cloudflare.api.token=${CLOUDFLARE_API_TOKEN}
cloudflare.account.id=${CLOUDFLARE_ACCOUNT_ID}
facebook.page-access-token=${FACEBOOK_PAGE_ACCESS_TOKEN}
facebook.page-id=${FACEBOOK_PAGE_ID}
instagram.business-id=${INSTAGRAM_BUSINESS_ID}
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}